blank_issues_enabled: false
contact_links:
  - name: Connect on LinkedIn
    url: https://www.linkedin.com/in/cynthia-teeters/
    about: For general discussion or networking, connect with me on LinkedIn.
